FichiersCartes = ["Compilation$Commande$0$00X0¤£££££.png",
"Ping$Commande$0$TS+0¤TS+0¤TS+0¤£££££.png",
"Run$Commande$0$00X0¤£££££.png",
"Debug$Commande$0$tS-0¤tS-0¤00X0¤£££££.png",
"Make$Commande$0$TA+0¤£££££.png",
".exe$Commande$0$MRµ0¤TR+0¤mR-0¤£££££.png",
"ls$Commande$0$mAµ0¤£££££.png",
"cd ~$Commande$0$=§µM¤£££££.png",
"apt update$Commande$0$TA+0¤TA+0¤TA+0¤00X0¤£££££.png",
"echo "" a.txt $Commande$0$tS-0¤TS+0¤£££££.png",
"exit()$Commande$0$tS@D¤tS@D¤TS@D¤£££££.png",
"kill$Commande$0$PA@D¤£££££.png",
"ctrl + C$Commande$0$MS@P¤£££££.png",
"ctrl + Z$Commande$0$PS@D¤£££££.png",
"ctrl + X$Commande$0$TS@m¤tS@M¤£££££.png",
"ctrl + Q$Commande$0$=§@m¤TS@t¤£££££.png",
"Alt F4$Commande$0$TR@D¤TS@D¤£££££.png",
"PrintScrean$Commande$0$MRµ0¤MRµ0¤£££££.png",
"rm -a$Commande$0$tS@D¤MS@D¤£££££.png",
"Virus alert$Erreur$0$tS@m¤PS@m¤£££££.png",
"Error 404$Erreur$0$TR@D¤PR@m¤£££££.png",
"Seg. fault$Erreur$0$PS@D¤PS@D¤00X0¤£££££.png",
"Insu. mem.$Erreur$0$PS@D¤tR@D¤£££££.png",
"Compilation error$Erreur$0$PS@D¤00X0¤£££££.png",
"Missing token$Erreur$0$PS@D¤00X0¤£££££.png",
"Server error$Erreur$0$MS@m¤tA-0¤£££££.png",
"Download$Commande$0$MS@T¤£££££.png",
"Upload$Commande$0$tA@M¤£££££.png",
"Fork bomb$Programme$8$£P§@T¤££=§@M¤££.png",
"Trojan$Programme$8$£P§@T¤££TA-0¤££.png",
"RansomWare$Programme$8$£P§@T¤£tS@T¤£££.png",
"Virus$Programme$14$£P§@T¤££tR@D¤££.png",
"Bug$Programme$8$£P§@T¤££TA-0¤££.png",
"Ubuntu$OS$11$£P§@T¤£TA+0¤TA+0¤£££.png",
"Debian$OS$7$£P§@T¤££££TA+0¤.png",
"Windows$OS$16$£P§@T¤£MS@m¤£££MS@m¤.png",
"Mac$OS$13$£P§@T¤££TA+0¤£TA+0¤£.png",
"Raspberrypy$Hardware$11$£P§@T¤££££MS@D¤.png",
"PFGA$Hardware$14$=§@M¤£P§@T¤££MAµ0¤££=§@M¤.png",
"RAM$Hardware$9$£P§@T¤££££MS@m¤.png",
"ROM$Hardware$13$£P§@T¤£££MS@D¤£.png",
"Server$Hardware$7$£P§@T¤£DS@T¤£££.png",
"Ethernet$Hardware$7$£P§@T¤£MS@T¤£££.png",
"Clef USB Trouvée$Hardware$14$£=§@m¤P§@T¤£TR@D¤£££.png",
"CourtCircuit$Hardware$22$£tA@D¤P§@T¤£tA@D¤TR+0¤£££.png",
"nano$Ide$11$£MRn0¤P§@T¤£tS-0¤TS+0¤£££.png",
"cat$Ide$8$£tS-0¤P§@T¤£TS+0¤£££.png",
"Qt$Ide$8$£tS-0¤P§@T¤£TS+0¤£££00X0¤.png",
"Eclipse$Ide$9$£=§@M¤P§@T¤£££P§X0¤£.png",
"VSCode$Ide$8$£=§@M¤P§@T¤£P§X0¤£££.png",
"Gcc$Compilateur$8$=§@M¤£P§@T¤££P§X0¤££.png",
"Debugger$Compilateur$14$£P§@T¤££tA-0¤£TA+0¤£.png",
"Mingw$Compilateur$9$££PSX0¤£P§@T¤££.png",
"Cmake$Compilateur$13$£££P§@T¤££PSX0¤PSX0¤.png",
"Python$Language$15$£P§@T¤££=§@M¤£MS@P¤£.png",
"JAVA$Language$24$£P§@T¤££=§@m¤=§@m¤=§@M¤££.png",
"VHDL$Language$12$=§@M¤=§@M¤£P§@T¤££ORµ0¤££.png",
"C++$Language$12$=§@M¤=§@M¤£P§@T¤££ORµ0¤££.png",
"RSA key$Bibliothèque$12$=§@M¤=§@M¤£P§@T¤££ORµ0¤££.png",
"OpenCV$Bibliothèque$12$=§@M¤=§@M¤£P§@T¤££ORµ0¤££.png",
"Cloud$Connection$12$=§@M¤=§@M¤£P§@T¤££ORµ0¤££.png",
"P2P$Connection$12$=§@M¤=§@M¤£P§@T¤££ORµ0¤££.png"
]